[project]
name = "dhs"
version = "0.1.0"
description = "dhs"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "flask==3.0.3",
  "numpy==2.1.2",
  "beautifulsoup4==4.12.3",
  "pwntools==4.13.1",
  "httpx==0.27.2",
  "lxml==5.3.0",
  "loguru==0.7.2",
  "selenium==4.25.0",
  "promise==2.3",
]
requires-python = "==3.13.0"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "tqdm==4.66.5",
]
