[project]
name = "ans"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "manim==0.18.1",
  "loguru==0.7.2"
]
# no python 3.13 on manim
requires-python = "==3.12.5"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false
