[project]
name = "pcfrv"
version = "0.2.9"
description = "PyComcigan Forked with Runtime Validation"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "fake-useragent==2.0.3",
  "httpx==0.28.1",
  "pydantic==2.10.6",
]

[tool.basedpyright]
reportAny = false

