[project]
name = "crystal"
version = "0.1.0"
description = "LLM that do things"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
  "gradio==6.0.2",
  "inquirer==3.4.1",
  "langchain-memgraph==0.1.11",
  "mem0ai[graph]@git+https://github.com/misilelab/mem0",
  "puremagic==1.30",
  "pydantic-ai-slim[duckduckgo,logfire,openai,mcp]==1.28.0",
  "rich==14.2.0",
]
